#!/usr/bin/env python

import sys, os, datetime, shutil

import common

def import_scores(org_abbr, scoredir, outdir):
    fns = os.listdir(scoredir)
    o = open("%s/%s" % (outdir, common.EVIDENCE_FILE), "w")
    o.write("#Generated by %s on %s\n" % (sys.argv[0], datetime.datetime.now()))
    o.write("#Species Reaction BLAST GTG\n")
    files = 0
    for fn in fns:
        if fn.endswith(".ecscores"):
           # print "The .ecscore file is %s" % fn
            orgname = org_abbr[fn[:-len(".ecscores")]]
	   # print "orgname is %s" % orgname
            f = open("%s/%s" % (scoredir, fn))
            files += 1
            for s in f:
                if s.startswith("#"):
                    continue
	#	print s
                ec, bs, bseq1, bseq2, gs, gseq1, gseq2 = s.strip().split("\t")
                o.write("%s\t%s\t%s\t%s\n" % (orgname, ec, bs, gs))
    if files == 0:
        raise Exception("No EC score files found!")

def import_cpds(cpdfn, outdir):
    target = "%s/%s" % (outdir, common.CPD_DIR)
    try:
        os.mkdir(target)
    except:
        pass
    print cpdfn
    shutil.copy("%s.blastpos" % (cpdfn), "%s/blastpos" % (target))
    shutil.copy("%s.blastneg" % (cpdfn), "%s/blastneg" % (target))
    shutil.copy("%s.gtgpos" % (cpdfn), "%s/gtgpos" % (target))
    shutil.copy("%s.gtgneg" % (cpdfn), "%s/gtgneg" % (target))

def import_tree(treefn, outdir):
    shutil.copy(treefn, "%s/tree" % (outdir))

def do_import(orglistfn, scoredir, cpddir, treefn, outdir):
    #copy tree.cpds and org_list.backup to target dir
    #?
    shutil.copy("/users/jianhou/work/model/model_training/tree_cpds/%s" % (common.TREE_CPD_FILE), "%s/%s" % (outdir, common.TREE_CPD_FILE))
    shutil.copy(orglistfn, "%s/%s" % (outdir, common.ORGANISM_LIST_FILE))
    org_abbr, org_long = common.read_organisms(outdir)
    import_scores(org_abbr, scoredir, outdir)
    import_cpds(cpddir, outdir)
    import_tree(treefn, outdir)
    
if __name__ == "__main__":
    orglistfn = sys.argv[1] # species list, e.g., org_list
    scoredir = sys.argv[2]  # dir with .ecscores
    cpdfn = sys.argv[3]     # filename body X, X.blastpos/X.blastneg/X.gtgpos/X.gtgneg
    treefn = sys.argv[4]    # input species tree
    outdir = sys.argv[5]    # project dir for reconstruction
    do_import(orglistfn, scoredir, cpdfn, treefn, outdir)
