#!/usr/bin/env python

import sys, os, datetime

import common

ddir = sys.argv[1]       # project dir
scoredir = sys.argv[2]   # dir with .ecscores
o = open("%s/%s" % (ddir, common.FULL_REACTION_SCORE_FILE), "w")

rscores, ecs = common.read_scores(ddir)
org_abbr, org_long = common.read_organisms(ddir)

fns = os.listdir(scoredir)
scores = {}
for fn in fns:
    if fn.endswith(".ecscores"):
        org = org_abbr[fn[:-len(".ecscores")]]
        scores[org] = {}
        f = open("%s/%s" % (scoredir, fn))
        for s in f:
            if s.startswith("#"):
                continue
            ec, bs, bs1, bs2, gs, gs1, gs2 = s.strip().split("\t")
            scores[org][ec] = (bs, bs1, bs2, gs, gs1, gs2)
            ecs.add(ec)

keys = set(rscores.keys())
#return set() keys with adding set(scores.keys())
keys.update(set(scores.keys()))
keys = list(keys)
keys.sort()
k2 = list(ecs)
k2.sort()
o.write("#Generated by %s on %s\n" % (" ".join(sys.argv), datetime.datetime.now()))
o.write("#EC Species PScore PNaiveScore PLogRatio BlastTreeScore GTGTreeScore BlastScore BlastSeq1 BlastSeq2 GTGScore GTGSeq1 GTGSeq2\n")

for species in keys:
    for ec in k2:
        if species in rscores:
            rscore = rscores[species][ec]
            #pfull, pnaive, pratio = rscores[species][ec]
        else:
            #pfull, pnaive, pratio = 0, 0, 0
            rscore = common.Score()
            rscore.pscore, rscore.npscore, rscore.logratio = 0, 0, 0
        if species in scores and ec in scores[species]:
            bs, bs1, bs2, gs, gs1, gs2 = scores[species][ec]
        else:
            bs = gs = 0
            bs1 = bs2 = gs1 = gs2 = "?"
        o.write("%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" % (ec, species, rscore, bs, bs1, bs2, gs, gs1, gs2))
